 **MC-8843 Aprendizaje Automático**

**Prof. MSc. Felipe Meza-Obando**

**Escuela de Ingeniería en Computación**

**Tecnológico de Costa Rica**

**Tarea #1**


**Objetivo:** Aprender a cargar datasets en una notebook en Google Colab desde
diferentes fuentes.

# **I.- Cargar Conjunto de Datos**

**Objetivo:** Aprender a cargar datasets en una notebook en Google Colab desde
diferentes fuentes.

**1.-Carga del conjunto de datos a la notebook en Colab desde un archivo CSV (o el que disponga para su set de datos) en Google Drive**

**a.- Primero, montar la unidad de Google Drive en la notebook:**

In [27]:
from google.colab import drive
drive.mount("/content/drive", force_remount=True)

Mounted at /content/drive

Al ejecutar esto, solicitará autorización. Se debe iniciar sesión y copiar el código generado.

**b.- Luego, identifica la ruta exacta del archivo CSV en tu Google Drive, por ejemplo:**
/content/drive/MyDrive/ruta_del_archivo/nombre_archivo.csv

**c.- Por último, usar pandas para cargar el archivo CSV:**

In [ ]:
import pandas as pd

In [30]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Tarea1/time_series_covid19_recovered_global.csv')

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,2/28/23,3/1/23,3/2/23,3/3/23,3/4/23,3/5/23,3/6/23,3/7/23,3/8/23,3/9/23
0,NaN,Afghanistan,33.93911,67.709953,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,NaN,Albania,41.15330,20.168300,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,NaN,Algeria,28.03390,1.659600,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,NaN,Andorra,42.50630,1.521800,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,NaN,Angola,-11.20270,17.873900,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

**d.- Ver las primeras 10 instancias para determinar si fué cargado correctamente**

In [33]:
df.head(10)

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,2/28/23,3/1/23,3/2/23,3/3/23,3/4/23,3/5/23,3/6/23,3/7/23,3/8/23,3/9/23
0,NaN,Afghanistan,33.93911,67.709953,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,NaN,Albania,41.15330,20.168300,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,NaN,Algeria,28.03390,1.659600,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,NaN,Andorra,42.50630,1.521800,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,NaN,Angola,-11.20270,17.873900,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,NaN,Antarctica,-71.94990,23.347000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,NaN,Antigua and Barbuda,17.06080,-61.796400,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,NaN,Argentina,-38.41610,-63.616700,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,NaN,Armenia,40.06910,45.038200,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,Australian Capital Territory,Australia,-35.47350,149.012400,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

**2. Cargar el conjunto de datos a la notebook en Colab desde su repositorio en
GitHub**

Copiar el enlace "raw" del archivo CSV en GitHub
  1.   Ir al archivo CSV en el repositorio GitHub.
  2.   Presionar el botón "Raw" que aparece arriba a la derecha del contenido del archivo
  3.   Copiar la URL que aparece en el navegador (esta URL termina normalmente en .csv

https://raw.githubusercontent.com/jasolano61/Sistemas-Ciberfisicos-y-Aprendizaje-automatico/refs/heads/main/AprendizajeAutomatico/tarea1/time_series_covid19_recovered_global.csv

In [32]:

url = 'https://raw.githubusercontent.com/jasolano61/Sistemas-Ciberfisicos-y-Aprendizaje-automatico/refs/heads/main/AprendizajeAutomatico/tarea1/time_series_covid19_recovered_global.csv'

# Carga directamente desde el enlace de GitHub
df = pd.read_csv(url)

# Muestra las 10 primeras filas para verificar
df.head(10)

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,2/28/23,3/1/23,3/2/23,3/3/23,3/4/23,3/5/23,3/6/23,3/7/23,3/8/23,3/9/23
0,NaN,Afghanistan,33.93911,67.709953,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,NaN,Albania,41.15330,20.168300,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,NaN,Algeria,28.03390,1.659600,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,NaN,Andorra,42.50630,1.521800,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,NaN,Angola,-11.20270,17.873900,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,NaN,Antarctica,-71.94990,23.347000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,NaN,Antigua and Barbuda,17.06080,-61.796400,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,NaN,Argentina,-38.41610,-63.616700,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,NaN,Armenia,40.06910,45.038200,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,Australian Capital Territory,Australia,-35.47350,149.012400,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

# II.- Exploración Inicial de Datos

**Objetivo:** Realizar una exploración inicial para comprender la estructura del
dataset